### ISSUE TITLE
Welcome to nginx on Debian!

### ISSUE THREAD

**Issue by fommil** [robertoandrade/docker-jitsi-meet#9]
Hi, thank you for putting this together! I'm hosting your container at

  https://meet.fommil.com/

with this script

```
docker rm -f jitsi-meet
docker pull robertoandrade/jitsi-meet
docker run -d \
       -e VIRTUAL_HOST=meet.fommil.com \
       -e LETSENCRYPT_HOST=meet.fommil.com \
       -e LETSENCRYPT_EMAIL="sam.halliday@gmail.com" \
       --expose=443 \
       --restart=always \
       --name=jitsi-meet \
       robertoandrade/jitsi-meet
```

and the nginx/lets-encrypt reverse proxy setup at https://github.com/jwilder/nginx-proxy (which basically handles creation of SSL certs and port forwarding etc).

But when I go to this location, I just see

> Welcome to nginx on Debian!
>
> If you see this page, the nginx web server is successfully installed and working on Debian. Further configuration is required.

etc, which looks like the container is not exposing the jitsi meet service at the root. Any ideas?

**Comment by fommil** [comment]
the logs are full of this kind of exception

```
JVB 2016-12-31 12:58:49.774 SEVERE: [20] org.jitsi.meet.ComponentMain.call().278 host-unknown, host:localhost, port:5347
org.xmpp.component.ComponentException: host-unknown
	at org.jivesoftware.whack.ExternalComponent.connect(ExternalComponent.java:219)
	at org.jivesoftware.whack.ExternalComponentManager.addComponent(ExternalComponentManager.java:221)
	at org.jivesoftware.whack.ExternalComponentManager.addComponent(ExternalComponentManager.java:201)
	at org.jitsi.meet.ComponentMain$3.call(ComponentMain.java:270)
	at org.jitsi.meet.ComponentMain$3.call(ComponentMain.java:255)
	at org.jitsi.retry.RetryStrategy$TaskRunner.run(RetryStrategy.java:193)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

```

is there maybe a hostname config that is missing? Is there maybe a config dir that we're supposed to map to the host?

**Comment by dalareo** [comment]
Any news here? I get the same error (but using localhost as development machine and no lets-nginx)

**Comment by anvarulugov** [comment]
Try with -p 443:443
